<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9631" started-at="2020-06-22T20:14:16 IST" finished-at="2020-06-22T20:14:26 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="9631" started-at="2020-06-22T20:14:16 IST" finished-at="2020-06-22T20:14:26 IST">
      <class name="week3.day2.uibank.UserLogin">
        <test-method status="PASS" signature="TC001_userLogin()[pri:0, instance:week3.day2.uibank.UserLogin@52feb982]" name="TC001_userLogin" duration-ms="7150" started-at="2020-06-22T20:14:16 IST" finished-at="2020-06-22T20:14:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_userLogin -->
      </class> <!-- week3.day2.uibank.UserLogin -->
      <class name="week3.day2.uibank.CreateAccount">
        <test-method status="FAIL" signature="TC002_createAccount()[pri:0, instance:week3.day2.uibank.CreateAccount@7a765367]" name="TC002_createAccount" duration-ms="2409" started-at="2020-06-22T20:14:24 IST" finished-at="2020-06-22T20:14:26 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code : 200 and actual :401 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code : 200 and actual :401 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at week3.day2.uibank.CreateAccount.TC002_createAccount(CreateAccount.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_createAccount -->
      </class> <!-- week3.day2.uibank.CreateAccount -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
